name: pr
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Non Visual Tests
        run: yarn test
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGILITYPORT }}'
          expires: 7d
          projectId: agilityport
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
